mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/bs659ff3817.json 46
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/cg028df0608.json 77
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/cs054qt7813.json 106
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/dv359zk3610.json 166
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/fc037kd5747.json 182
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/fg106xz0738.json 195
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/fg600ph4255.json 196
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/fs409zn9131.json 222
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/ft438ns7558.json 228
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/fx828qq3836.json 241
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/gh175dc4875.json 266
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/gr186rh7096.json 293
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/hn424kr6627.json 329
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/jc904jt1675.json 366
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/nd924vn8802.json 520
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/ph299bg5284.json 582
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/qj416gs4700.json 642
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/sc758qq3548.json 730
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/sr082bp9988.json 762
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/sy953kp6030.json 780
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/td541nx4976.json 789
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/tq652gg2776.json 812
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/vc391bq0493.json 846
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/vd420js0307.json 849
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/wb331cc0063.json 905
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/wj252dn6880.json 926
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/wr512rp0028.json 943
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/wv378vq3043.json 957
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/ww637df6344.json 960
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/wz728bt5394.json 969
mapedge trace -s ./series/stanford/japan/default.json -s ./series/stanford/japan/smaller_layout_less_wide.json /scratch/iiif_cache/japan/xv324bq8642.json 1012
